package dal.mitacsgri.treecare.consts

/**
 * Created by Devansh on 25-06-2019
 */

//Modes
const val STARTER_MODE = 0
const val CHALLENGER_MODE = 1
const val TOURNAMENT_MODE = 2

//Mode colors
const val STARTER_MODE_SOLID_COLOR = "FF0189F1"
const val STARTER_MODE_STROKE_COLOR = "FF0000FF"
const val CHALLENGER_MODE_SOLID_COLOR = "FFFF6F00"
const val CHALLENGER_MODE_STROKE_COLOR = "FFC43E00"
const val TOURNAMENT_MODE_SOLID_COLOR = "FF9C27B0"
const val TOURNAMENT_MODE_STROKE_COLOR = "FFFF6F00"

const val CHALLENGE_TYPE_DAILY_GOAL_BASED = 0
const val CHALLENGE_TYPE_AGGREGATE_BASED = 1